

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EM_ConProjects.Models.DataModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Projects_DBContainer : DbContext
{
    public Projects_DBContainer()
        : base("name=Projects_DBContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Projects> Projects { get; set; }

    public virtual DbSet<Localities> Localities { get; set; }

    public virtual DbSet<Contractors> Contractors { get; set; }

    public virtual DbSet<Actions> Actions { get; set; }

}

}

